//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adventureworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comentario
    {
        public int comentario_id { get; set; }
        public Nullable<int> usuario_id { get; set; }
        public string comentario_subject { get; set; }
        public string comentario_body { get; set; }
        public int foto_id { get; set; }
    
        public virtual foto foto { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
